// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oidb_head_v2.proto

package pbv2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Oidb2ServerSsoInfo struct {
	Uint32Seq              *uint32  `protobuf:"varint,1,opt,name=uint32_seq,json=uint32Seq" json:"uint32_seq,omitempty"`
	Uint32AppId            *uint32  `protobuf:"varint,2,opt,name=uint32_app_id,json=uint32AppId" json:"uint32_app_id,omitempty"`
	BytesImei              []byte   `protobuf:"bytes,3,opt,name=bytes_imei,json=bytesImei" json:"bytes_imei,omitempty"`
	BytesClientVersion     []byte   `protobuf:"bytes,4,opt,name=bytes_client_version,json=bytesClientVersion" json:"bytes_client_version,omitempty"`
	BytesSsoClientVersion  []byte   `protobuf:"bytes,5,opt,name=bytes_sso_client_version,json=bytesSsoClientVersion" json:"bytes_sso_client_version,omitempty"`
	Uint32SsoBid           *uint32  `protobuf:"varint,6,opt,name=uint32_sso_bid,json=uint32SsoBid" json:"uint32_sso_bid,omitempty"`
	Uint32SsoClientVersion *uint32  `protobuf:"varint,10,opt,name=uint32_sso_client_version,json=uint32SsoClientVersion" json:"uint32_sso_client_version,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Oidb2ServerSsoInfo) Reset()         { *m = Oidb2ServerSsoInfo{} }
func (m *Oidb2ServerSsoInfo) String() string { return proto.CompactTextString(m) }
func (*Oidb2ServerSsoInfo) ProtoMessage()    {}
func (*Oidb2ServerSsoInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2820a8a73175fb7, []int{0}
}

func (m *Oidb2ServerSsoInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Oidb2ServerSsoInfo.Unmarshal(m, b)
}
func (m *Oidb2ServerSsoInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Oidb2ServerSsoInfo.Marshal(b, m, deterministic)
}
func (m *Oidb2ServerSsoInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Oidb2ServerSsoInfo.Merge(m, src)
}
func (m *Oidb2ServerSsoInfo) XXX_Size() int {
	return xxx_messageInfo_Oidb2ServerSsoInfo.Size(m)
}
func (m *Oidb2ServerSsoInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Oidb2ServerSsoInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Oidb2ServerSsoInfo proto.InternalMessageInfo

func (m *Oidb2ServerSsoInfo) GetUint32Seq() uint32 {
	if m != nil && m.Uint32Seq != nil {
		return *m.Uint32Seq
	}
	return 0
}

func (m *Oidb2ServerSsoInfo) GetUint32AppId() uint32 {
	if m != nil && m.Uint32AppId != nil {
		return *m.Uint32AppId
	}
	return 0
}

func (m *Oidb2ServerSsoInfo) GetBytesImei() []byte {
	if m != nil {
		return m.BytesImei
	}
	return nil
}

func (m *Oidb2ServerSsoInfo) GetBytesClientVersion() []byte {
	if m != nil {
		return m.BytesClientVersion
	}
	return nil
}

func (m *Oidb2ServerSsoInfo) GetBytesSsoClientVersion() []byte {
	if m != nil {
		return m.BytesSsoClientVersion
	}
	return nil
}

func (m *Oidb2ServerSsoInfo) GetUint32SsoBid() uint32 {
	if m != nil && m.Uint32SsoBid != nil {
		return *m.Uint32SsoBid
	}
	return 0
}

func (m *Oidb2ServerSsoInfo) GetUint32SsoClientVersion() uint32 {
	if m != nil && m.Uint32SsoClientVersion != nil {
		return *m.Uint32SsoClientVersion
	}
	return 0
}

type LoginSig struct {
	Uint32Type           *uint32  `protobuf:"varint,1,opt,name=uint32_type,json=uint32Type" json:"uint32_type,omitempty"`
	BytesSig             []byte   `protobuf:"bytes,2,opt,name=bytes_sig,json=bytesSig" json:"bytes_sig,omitempty"`
	Uint32Appid          *uint32  `protobuf:"varint,3,opt,name=uint32_appid,json=uint32Appid" json:"uint32_appid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginSig) Reset()         { *m = LoginSig{} }
func (m *LoginSig) String() string { return proto.CompactTextString(m) }
func (*LoginSig) ProtoMessage()    {}
func (*LoginSig) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2820a8a73175fb7, []int{1}
}

func (m *LoginSig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginSig.Unmarshal(m, b)
}
func (m *LoginSig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginSig.Marshal(b, m, deterministic)
}
func (m *LoginSig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginSig.Merge(m, src)
}
func (m *LoginSig) XXX_Size() int {
	return xxx_messageInfo_LoginSig.Size(m)
}
func (m *LoginSig) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginSig.DiscardUnknown(m)
}

var xxx_messageInfo_LoginSig proto.InternalMessageInfo

func (m *LoginSig) GetUint32Type() uint32 {
	if m != nil && m.Uint32Type != nil {
		return *m.Uint32Type
	}
	return 0
}

func (m *LoginSig) GetBytesSig() []byte {
	if m != nil {
		return m.BytesSig
	}
	return nil
}

func (m *LoginSig) GetUint32Appid() uint32 {
	if m != nil && m.Uint32Appid != nil {
		return *m.Uint32Appid
	}
	return 0
}

type OIDBHead struct {
	Uint64Uin                    *uint64             `protobuf:"varint,1,opt,name=uint64_uin,json=uint64Uin" json:"uint64_uin,omitempty"`
	Uint32Command                *uint32             `protobuf:"varint,2,opt,name=uint32_command,json=uint32Command" json:"uint32_command,omitempty"`
	Uint32ServiceType            *uint32             `protobuf:"varint,3,opt,name=uint32_service_type,json=uint32ServiceType" json:"uint32_service_type,omitempty"`
	Uint32Seq                    *uint32             `protobuf:"varint,4,opt,name=uint32_seq,json=uint32Seq" json:"uint32_seq,omitempty"`
	Uint32ClientAddr             *uint32             `protobuf:"fixed32,5,opt,name=uint32_client_addr,json=uint32ClientAddr" json:"uint32_client_addr,omitempty"`
	BytesClientAddr              []byte              `protobuf:"bytes,15,opt,name=bytes_client_addr,json=bytesClientAddr" json:"bytes_client_addr,omitempty"`
	Uint32ServerAddr             *uint32             `protobuf:"fixed32,6,opt,name=uint32_server_addr,json=uint32ServerAddr" json:"uint32_server_addr,omitempty"`
	BytesServerAddr              []byte              `protobuf:"bytes,16,opt,name=bytes_server_addr,json=bytesServerAddr" json:"bytes_server_addr,omitempty"`
	Uint32Result                 *uint32             `protobuf:"varint,7,opt,name=uint32_result,json=uint32Result" json:"uint32_result,omitempty"`
	StrErrorMsg                  *string             `protobuf:"bytes,8,opt,name=str_error_msg,json=strErrorMsg" json:"str_error_msg,omitempty"`
	MsgLoginSig                  *LoginSig           `protobuf:"bytes,9,opt,name=msg_login_sig,json=msgLoginSig" json:"msg_login_sig,omitempty"`
	StrUserName                  *string             `protobuf:"bytes,10,opt,name=str_user_name,json=strUserName" json:"str_user_name,omitempty"`
	StrServiceName               *string             `protobuf:"bytes,11,opt,name=str_service_name,json=strServiceName" json:"str_service_name,omitempty"`
	Uint32Flag                   *uint32             `protobuf:"varint,12,opt,name=uint32_flag,json=uint32Flag" json:"uint32_flag,omitempty"`
	Uint32FromAddr               *uint32             `protobuf:"varint,13,opt,name=uint32_from_addr,json=uint32FromAddr" json:"uint32_from_addr,omitempty"`
	Uint32LocalAddr              *uint32             `protobuf:"varint,14,opt,name=uint32_local_addr,json=uint32LocalAddr" json:"uint32_local_addr,omitempty"`
	Uint32Moduleid               *uint32             `protobuf:"varint,17,opt,name=uint32_moduleid,json=uint32Moduleid" json:"uint32_moduleid,omitempty"`
	Reserved                     []byte              `protobuf:"bytes,18,opt,name=reserved" json:"reserved,omitempty"`
	Uint32LocaleId               *uint32             `protobuf:"varint,19,opt,name=uint32_locale_id,json=uint32LocaleId" json:"uint32_locale_id,omitempty"`
	MsgSsoInfo                   *Oidb2ServerSsoInfo `protobuf:"bytes,20,opt,name=msg_sso_info,json=msgSsoInfo" json:"msg_sso_info,omitempty"`
	BytesServiceInfo             []byte              `protobuf:"bytes,2000,opt,name=bytes_service_info,json=bytesServiceInfo" json:"bytes_service_info,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}            `json:"-"`
	proto.XXX_InternalExtensions `json:"-"`
	XXX_unrecognized             []byte `json:"-"`
	XXX_sizecache                int32  `json:"-"`
}

func (m *OIDBHead) Reset()         { *m = OIDBHead{} }
func (m *OIDBHead) String() string { return proto.CompactTextString(m) }
func (*OIDBHead) ProtoMessage()    {}
func (*OIDBHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2820a8a73175fb7, []int{2}
}

var extRange_OIDBHead = []proto.ExtensionRange{
	{Start: 1000, End: 1999},
}

func (*OIDBHead) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_OIDBHead
}

func (m *OIDBHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OIDBHead.Unmarshal(m, b)
}
func (m *OIDBHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OIDBHead.Marshal(b, m, deterministic)
}
func (m *OIDBHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OIDBHead.Merge(m, src)
}
func (m *OIDBHead) XXX_Size() int {
	return xxx_messageInfo_OIDBHead.Size(m)
}
func (m *OIDBHead) XXX_DiscardUnknown() {
	xxx_messageInfo_OIDBHead.DiscardUnknown(m)
}

var xxx_messageInfo_OIDBHead proto.InternalMessageInfo

func (m *OIDBHead) GetUint64Uin() uint64 {
	if m != nil && m.Uint64Uin != nil {
		return *m.Uint64Uin
	}
	return 0
}

func (m *OIDBHead) GetUint32Command() uint32 {
	if m != nil && m.Uint32Command != nil {
		return *m.Uint32Command
	}
	return 0
}

func (m *OIDBHead) GetUint32ServiceType() uint32 {
	if m != nil && m.Uint32ServiceType != nil {
		return *m.Uint32ServiceType
	}
	return 0
}

func (m *OIDBHead) GetUint32Seq() uint32 {
	if m != nil && m.Uint32Seq != nil {
		return *m.Uint32Seq
	}
	return 0
}

func (m *OIDBHead) GetUint32ClientAddr() uint32 {
	if m != nil && m.Uint32ClientAddr != nil {
		return *m.Uint32ClientAddr
	}
	return 0
}

func (m *OIDBHead) GetBytesClientAddr() []byte {
	if m != nil {
		return m.BytesClientAddr
	}
	return nil
}

func (m *OIDBHead) GetUint32ServerAddr() uint32 {
	if m != nil && m.Uint32ServerAddr != nil {
		return *m.Uint32ServerAddr
	}
	return 0
}

func (m *OIDBHead) GetBytesServerAddr() []byte {
	if m != nil {
		return m.BytesServerAddr
	}
	return nil
}

func (m *OIDBHead) GetUint32Result() uint32 {
	if m != nil && m.Uint32Result != nil {
		return *m.Uint32Result
	}
	return 0
}

func (m *OIDBHead) GetStrErrorMsg() string {
	if m != nil && m.StrErrorMsg != nil {
		return *m.StrErrorMsg
	}
	return ""
}

func (m *OIDBHead) GetMsgLoginSig() *LoginSig {
	if m != nil {
		return m.MsgLoginSig
	}
	return nil
}

func (m *OIDBHead) GetStrUserName() string {
	if m != nil && m.StrUserName != nil {
		return *m.StrUserName
	}
	return ""
}

func (m *OIDBHead) GetStrServiceName() string {
	if m != nil && m.StrServiceName != nil {
		return *m.StrServiceName
	}
	return ""
}

func (m *OIDBHead) GetUint32Flag() uint32 {
	if m != nil && m.Uint32Flag != nil {
		return *m.Uint32Flag
	}
	return 0
}

func (m *OIDBHead) GetUint32FromAddr() uint32 {
	if m != nil && m.Uint32FromAddr != nil {
		return *m.Uint32FromAddr
	}
	return 0
}

func (m *OIDBHead) GetUint32LocalAddr() uint32 {
	if m != nil && m.Uint32LocalAddr != nil {
		return *m.Uint32LocalAddr
	}
	return 0
}

func (m *OIDBHead) GetUint32Moduleid() uint32 {
	if m != nil && m.Uint32Moduleid != nil {
		return *m.Uint32Moduleid
	}
	return 0
}

func (m *OIDBHead) GetReserved() []byte {
	if m != nil {
		return m.Reserved
	}
	return nil
}

func (m *OIDBHead) GetUint32LocaleId() uint32 {
	if m != nil && m.Uint32LocaleId != nil {
		return *m.Uint32LocaleId
	}
	return 0
}

func (m *OIDBHead) GetMsgSsoInfo() *Oidb2ServerSsoInfo {
	if m != nil {
		return m.MsgSsoInfo
	}
	return nil
}

func (m *OIDBHead) GetBytesServiceInfo() []byte {
	if m != nil {
		return m.BytesServiceInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Oidb2ServerSsoInfo)(nil), "pbv2.Oidb2ServerSsoInfo")
	proto.RegisterType((*LoginSig)(nil), "pbv2.LoginSig")
	proto.RegisterType((*OIDBHead)(nil), "pbv2.OIDBHead")
}

func init() { proto.RegisterFile("oidb_head_v2.proto", fileDescriptor_c2820a8a73175fb7) }

var fileDescriptor_c2820a8a73175fb7 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x54, 0xed, 0x6e, 0xd3, 0x30,
	0x14, 0x55, 0x47, 0xe9, 0x5a, 0xf7, 0x73, 0xde, 0x40, 0x01, 0x84, 0x28, 0x05, 0x44, 0x35, 0x41,
	0x85, 0xca, 0x34, 0x04, 0xff, 0xb6, 0xc1, 0x44, 0xa5, 0x8d, 0x49, 0x29, 0xe3, 0xaf, 0x95, 0xd6,
	0x77, 0xc1, 0x22, 0x8e, 0x33, 0x3b, 0xad, 0xb4, 0xd7, 0xe3, 0x09, 0xf6, 0x18, 0xbc, 0x01, 0x7f,
	0x91, 0xaf, 0x9d, 0x36, 0x1d, 0x3f, 0x73, 0xef, 0xb9, 0xe7, 0xda, 0xe7, 0x9c, 0x98, 0x50, 0x25,
	0xf8, 0x8c, 0xfd, 0x84, 0x88, 0xb3, 0xe5, 0x78, 0x94, 0x69, 0x95, 0x2b, 0x5a, 0xcd, 0x66, 0xcb,
	0xf1, 0xe0, 0xf7, 0x16, 0xa1, 0x17, 0x82, 0xcf, 0xc6, 0x53, 0xd0, 0x4b, 0xd0, 0x53, 0xa3, 0x26,
	0xe9, 0x95, 0xa2, 0x4f, 0x09, 0x59, 0x88, 0x34, 0x7f, 0x3f, 0x66, 0x06, 0xae, 0x83, 0x4a, 0xbf,
	0x32, 0x6c, 0x87, 0x0d, 0x57, 0x99, 0xc2, 0x35, 0x1d, 0x90, 0xb6, 0x6f, 0x47, 0x59, 0xc6, 0x04,
	0x0f, 0xb6, 0x10, 0xd1, 0x74, 0xc5, 0xa3, 0x2c, 0x9b, 0x70, 0x4b, 0x31, 0xbb, 0xc9, 0xc1, 0x30,
	0x21, 0x41, 0x04, 0xf7, 0xfa, 0x95, 0x61, 0x2b, 0x6c, 0x60, 0x65, 0x22, 0x41, 0xd0, 0x77, 0x64,
	0xcf, 0xb5, 0xe7, 0x89, 0x80, 0x34, 0x67, 0x4b, 0xd0, 0x46, 0xa8, 0x34, 0xa8, 0x22, 0x90, 0x62,
	0xef, 0x04, 0x5b, 0x3f, 0x5c, 0x87, 0x7e, 0x20, 0x81, 0x9b, 0x30, 0x46, 0xdd, 0x9d, 0xba, 0x8f,
	0x53, 0x0f, 0xb0, 0x3f, 0x35, 0x6a, 0x73, 0xf0, 0x25, 0xe9, 0x14, 0x97, 0x31, 0x8a, 0xcd, 0x04,
	0x0f, 0x6a, 0x78, 0xdc, 0x96, 0xbf, 0x90, 0x51, 0xc7, 0x82, 0xd3, 0x8f, 0xe4, 0x51, 0x09, 0x75,
	0x87, 0x9f, 0xe0, 0xc0, 0xc3, 0xd5, 0xc0, 0xc6, 0x82, 0xc1, 0x2f, 0x52, 0x3f, 0x53, 0xb1, 0x48,
	0xa7, 0x22, 0xa6, 0xcf, 0x88, 0x57, 0x81, 0xe5, 0x37, 0x19, 0x78, 0xe9, 0xbc, 0x98, 0xdf, 0x6f,
	0x32, 0xa0, 0x4f, 0x48, 0xc3, 0x5f, 0x43, 0xc4, 0xa8, 0x5b, 0x2b, 0xac, 0xbb, 0x73, 0x8b, 0x98,
	0x3e, 0x27, 0xad, 0xb5, 0xb0, 0x82, 0xa3, 0x6c, 0x65, 0x5d, 0x05, 0x1f, 0xfc, 0xad, 0x91, 0xfa,
	0xc5, 0xe4, 0xf3, 0xf1, 0x57, 0x88, 0x78, 0xe1, 0xd3, 0xe1, 0x01, 0x5b, 0x88, 0x14, 0x97, 0x55,
	0x9d, 0x4f, 0x87, 0x07, 0x97, 0x22, 0xa5, 0xaf, 0x56, 0x37, 0x9f, 0x2b, 0x29, 0xa3, 0xb4, 0x30,
	0xca, 0xbb, 0x77, 0xe2, 0x8a, 0x74, 0x44, 0x76, 0x57, 0x6e, 0xeb, 0xa5, 0x98, 0x83, 0x3b, 0xbb,
	0x5b, 0xbe, 0x53, 0xd8, 0x8e, 0x1d, 0xbc, 0xc2, 0x66, 0x3a, 0xaa, 0x77, 0xd3, 0xf1, 0x86, 0xd0,
	0x62, 0xab, 0x53, 0x31, 0xe2, 0x5c, 0xa3, 0x45, 0xdb, 0x61, 0xcf, 0x6f, 0xc6, 0xc6, 0x11, 0xe7,
	0x9a, 0xee, 0x93, 0x9d, 0x8d, 0x20, 0x20, 0xb8, 0x8b, 0xba, 0x74, 0x4b, 0x29, 0x40, 0xec, 0x9a,
	0xd9, 0x60, 0x5c, 0x1d, 0xb8, 0x56, 0x66, 0x76, 0x39, 0xde, 0x64, 0x2e, 0x83, 0x7b, 0x25, 0xe6,
	0x12, 0xf6, 0xc5, 0x2a, 0xd1, 0x1a, 0xcc, 0x22, 0xc9, 0x83, 0xed, 0x72, 0x44, 0x42, 0xac, 0xd9,
	0xd8, 0x9b, 0x5c, 0x33, 0xd0, 0x5a, 0x69, 0x26, 0x4d, 0x1c, 0xd4, 0xfb, 0x95, 0x61, 0x23, 0x6c,
	0x9a, 0x5c, 0x7f, 0xb1, 0xb5, 0x73, 0x13, 0xd3, 0x31, 0x69, 0x4b, 0x13, 0xb3, 0xc4, 0xe6, 0x01,
	0x2d, 0x6e, 0xf4, 0x2b, 0xc3, 0xe6, 0xb8, 0x33, 0xb2, 0xbf, 0xdb, 0xa8, 0x88, 0x49, 0xd8, 0x94,
	0x26, 0x5e, 0x65, 0xc6, 0xf3, 0x2e, 0x0c, 0x68, 0x96, 0x46, 0x12, 0x30, 0x6e, 0x8e, 0xf7, 0xd2,
	0x80, 0xfe, 0x16, 0x49, 0xa0, 0x43, 0xd2, 0xb3, 0x98, 0xc2, 0x20, 0x84, 0x35, 0x11, 0xd6, 0x31,
	0xb9, 0xf6, 0xee, 0x20, 0x72, 0x9d, 0xc0, 0xab, 0x24, 0x8a, 0x83, 0x56, 0x39, 0x81, 0xa7, 0x49,
	0x14, 0x5b, 0xaa, 0x02, 0xa0, 0x95, 0x74, 0xb2, 0xb4, 0x11, 0xe5, 0xd3, 0x72, 0xaa, 0x95, 0x2c,
	0x14, 0xf4, 0xc8, 0x44, 0xcd, 0xa3, 0xc4, 0x41, 0x3b, 0x08, 0xed, 0xba, 0xc6, 0x99, 0xad, 0x23,
	0xf6, 0x35, 0xf1, 0x25, 0x26, 0x15, 0x5f, 0x24, 0x20, 0x78, 0xb0, 0x53, 0x26, 0x3d, 0xf7, 0x55,
	0xfa, 0x98, 0xd4, 0x35, 0xa0, 0x25, 0x3c, 0xa0, 0x2e, 0xff, 0xc5, 0x77, 0xe9, 0x68, 0xb8, 0x10,
	0xec, 0xdb, 0xb2, 0x5b, 0x66, 0xc1, 0x7d, 0x30, 0xe1, 0xf4, 0x13, 0x69, 0x59, 0x9d, 0xed, 0xbf,
	0x2a, 0xd2, 0x2b, 0x15, 0xec, 0xa1, 0xcc, 0x81, 0x93, 0xf9, 0xff, 0x17, 0x2d, 0x24, 0xd2, 0xc4,
	0xc5, 0xeb, 0xf6, 0x96, 0xd0, 0x75, 0x30, 0xac, 0x9a, 0xc8, 0x70, 0xeb, 0x42, 0xd7, 0x5b, 0x45,
	0x43, 0xcc, 0xc1, 0xc2, 0xf7, 0x6b, 0xf5, 0x3f, 0xdb, 0xbd, 0xdb, 0xee, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xd1, 0x8a, 0x70, 0x7d, 0x46, 0x05, 0x00, 0x00,
}
